name: Bug Report
description: Report a bug in the functionality of Tea Framework.
labels: ["status: unresolved", "type: feature proposal"]

body:
- type: markdown
  attributes:
    value: |
      _Tea Framework_ is a library and framework loaded as a mod for [tModLoader](https://github.com/tModLoader/tModLoader).

      Please fill out all the necessary details. 
      Please only report an issue if you are certain it is caused by Tea Framework.

      Issues with installation of the mod are not suitable for out issue tracker, ask for help in our [Discord](https://discord.gg/thorium) instead.

- type: markdown
  attributes:
    value: |
      ## Is there an existing issue for this?
      Please ensure that no one has already reported this issue.

- type: dropdown
  attributes:
    label: OS
    description: What operating system are you on?
    multiple: false
    options:
      - Windows
      - MacOS
      - Linux
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    id: description
    description: |
      Describe your issue here.
      Please keep this as concise. You may elaborate in a later text area. 
      For example: "When I press X button in menu Y, the component Z becomes unclickable"

- type: textarea
  attributes:
    label: Log File
    description: |
      Please attach your `client.log` (as well as `server.log`, if applicable) file(s) here.
      They may be found inside of the `tModLoader-Logs` directory in your installation directory.

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe the steps to reproduce this issue.
    placeholder: |
      1. [First Step]
      2. [Second Step]
      3. [And so on...]

- type: textarea
  attributes:
    label: Expected behavior
    description: |
      What should be happening? If you don't know, leave what you think should happen.

- type: textarea
  attributes:
    label: Actual behavior
    description: |
      What is actually happening? Feel free to use images to help describe what you are experiencing.
      
- type: textarea
  attributes:
    label: Reproduction frequency
    description: |
      How often are you able to reproduce the issue? How reliable is the reproduction?

- type: textarea
  attributes:
    label: Additional information
    description: |
       Any additional information, configuration, or data that might be necessary to reproduce the issue.
       You may use this to elaborate on the description.
