blank_issues_enabled: true
contact_links:
 - name: Discord Server
   url: https://discord.gg/Y8bvvqyFQw
   about: |
    Please direct help questions and support questions here prior to filing an issue.
    If you are unsure whether something is an issue, ask here first.
